services:
  app:
    build:
      context: .  
    volumes:
      - .:/app  
    command: npm test
    ports:
      - "8080:8080" 
    environment:
      NODE_ENV: test
    networks:
      proxy_net:
        ipv4_address: 192.168.1.2


networks:
  proxy_net: 
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"
        
